# Generated by Django 3.2.9 on 2021-12-22 15:07

import apps.user.validators
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=40, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('dni', models.CharField(max_length=8, null=True, validators=[apps.user.validators.dni])),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=9, null=True)),
                ('birthday', models.DateField(null=True, validators=[apps.user.validators.fechaNacimiento])),
                ('type_sex', models.PositiveSmallIntegerField(choices=[(0, ' '), (1, 'MAN'), (2, 'WOMAN')], default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2)])),
                ('is_admin', models.BooleanField(default=False, verbose_name='super administrador')),
                ('is_active', models.BooleanField(default=True, verbose_name='estado')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='super usuario')),
                ('is_staff', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Diseases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enfDiabetes', models.CharField(default='null', max_length=500)),
                ('enfHipertension', models.CharField(default='null', max_length=500)),
                ('enfObesidad', models.CharField(default='null', max_length=500)),
                ('enfDislipidemias', models.CharField(default='null', max_length=500)),
                ('enfCardiopatia', models.CharField(default='null', max_length=500)),
                ('enfCancer', models.CharField(default='null', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Physical_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumeAlcohol', models.CharField(max_length=800, null=True)),
                ('fuma', models.CharField(max_length=800, null=True)),
                ('otros', models.CharField(max_length=800, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Symptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssestrenimiento', models.CharField(max_length=20, null=True)),
                ('ssdiarrea', models.CharField(max_length=20, null=True)),
                ('sscefalea', models.CharField(max_length=20, null=True)),
                ('ssvomito', models.CharField(max_length=20, null=True)),
                ('ssfiebre', models.CharField(max_length=20, null=True)),
                ('ssdebilidad', models.CharField(max_length=20, null=True)),
                ('ssfaltapetito', models.CharField(max_length=20, null=True)),
                ('ssgananciapeso', models.CharField(max_length=20, null=True)),
                ('ssperdidapeso', models.CharField(max_length=20, null=True)),
                ('ssedema', models.CharField(max_length=20, null=True)),
                ('sstumoracion', models.CharField(max_length=20, null=True)),
                ('proximaCita', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Eating_Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('req_calories', models.FloatField(null=True)),
                ('req_proteins', models.FloatField(null=True)),
                ('req_carbohydrates', models.FloatField(null=True)),
                ('req_fats', models.FloatField(null=True)),
                ('req_vitamins', models.FloatField(null=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
