# Generated by Django 3.2.9 on 2021-12-22 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.TextField(null=True)),
                ('image_url', models.TextField(null=True)),
                ('ingredients', models.TextField(null=True)),
                ('nutrition', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='History_Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_foodmeal', models.TextField(null=True)),
                ('calories', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Food_Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idFood', to='food.food')),
                ('id_meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idMeal', to='food.meal')),
                ('id_type_food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idTypeFood', to='food.typefood')),
            ],
        ),
    ]
